version: '3.8'
services:
  backend:
    build: ./backend
    networks:
      - lemoncode-challenge
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://some-mongo:27017

  frontend:
    build: ./frontend
    networks:
      - lemoncode-challenge
    ports:
      - "8080:5000"
    environment:
      - API_URL=http://topics-api:5000/api/topics

  mongodb:
    image: mongo:4
    networks:
      - lemoncode-challenge
    volumes:
      - /data/db
    command: mongod
    environment:
      - DATABASE_URL=mongodb://localhost:27017
      - DATABASE_NAME=TopicstoreDb
      - HOST=localhost
      - PORT=5000

networks:
  lemoncode-challenge: