version: '3.9'
services:
  frontend:
    build: 
      context: ./frontend
      # dockerfile: Dockerfile    
    deploy:
      replicas: 2
    ports:
      - 3000
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend      
      # dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest